name: Snigdha OS Arctic

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install Git
        run: |
          pacman -Syy --noconfirm
          pacman -S --noconfirm git
          pacman -S --noconfirm archiso
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build snigdha os
        run: |
          cd scripts
          ./01-online-build