name: Build ArchISO

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo pacman -Syu --noconfirm
        sudo pacman -S --noconfirm archiso git

    - name: Clone ArchISO repository
      run: git clone https://github.com/Snigdha-OS/snigdhaos-arctic.git

    - name: Build ArchISO image
      run: |
        cd scripts
        sudo ./01-online-build

    - name: Upload built ISO artifact
      uses: actions/upload-artifact@v2
      with:
        name: snigdhaos-arctic
        path: output/*.iso
