name: Mirror to GitLab

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Mirror to GitLab
        env:
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        run: |
          git remote add gitlab https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@${GITLAB_REPO##*/}.git
          git config --global push.default mirror
          git push --mirror gitlab